language: python

python:
  - "2.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in secrets.py.enc -out secrets.py -d

install:
  - pip install -r requirements.txt

script:
  - python main.py