runtime: python37

env_variables:
ID: '1163e4fb05aa45238012c33970bb7095'
SECRET: 'bf8085c460dd4177b9b897d0e5ce9a58'
SECRET_KEY: 'geominfun'

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

